name: coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2.4.2

    - name: Use Node.js
      uses: actions/setup-node@v3.1.1
        
    - run: npm install
    - run: npm audit fix
    - run: npm run test
    
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
